package SISGECM;

import java.sql.*;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Ingeniero Brayan
 */
public class ModificaCitas extends javax.swing.JFrame {
    
    Medicos medico;

    private static int idmedico;
    Conexion c = new Conexion();
    public ModificaCitas() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/img/icono.png")).getImage());
        
        this.paciente_txt.setEditable(false);
        this.medico_txt.setEditable(false);
        this.hora_actual_txt.setEditable(false);
        this.nueva_hora_txt.setEditable(false);
        this.cambiar_med_btn.setEnabled(false);
        this.busca_horario_btn.setEnabled(false);
        this.modificar_btn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        busqueda_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        paciente_txt = new javax.swing.JTextField();
        buscar_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        medico_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dia_txt = new com.toedter.calendar.JDateChooser();
        hora_slc = new javax.swing.JComboBox();
        modificar_btn = new javax.swing.JButton();
        busca_horario_btn = new javax.swing.JButton();
        hora_actual_txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cancelar_btn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        nueva_hora_txt = new javax.swing.JTextField();
        cambiar_med_btn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MODIFICAR DATOS DE CITA");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("MODIFICAR CITA");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Documento:");

        busqueda_txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Paciente:");

        paciente_txt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        buscar_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buscar_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N
        buscar_btn.setText("BUSCAR");
        buscar_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_btnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Médico:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Dia:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Hora:");

        hora_slc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                hora_slcItemStateChanged(evt);
            }
        });

        modificar_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        modificar_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update.png"))); // NOI18N
        modificar_btn.setText("MODIFICAR");
        modificar_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modificar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificar_btnActionPerformed(evt);
            }
        });

        busca_horario_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N
        busca_horario_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        busca_horario_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busca_horario_btnActionPerformed(evt);
            }
        });

        jLabel7.setText("Actual:");

        jLabel8.setText("Disponibles:");

        cancelar_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cancelar_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar.png"))); // NOI18N
        cancelar_btn.setText("CANCELAR");
        cancelar_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar_btnActionPerformed(evt);
            }
        });

        jLabel9.setText("Nueva Hora:");

        cambiar_med_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cambiar_med_btn.setText("CAMBIAR");
        cambiar_med_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cambiar_med_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiar_med_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(modificar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(cancelar_btn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(busqueda_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buscar_btn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dia_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(busca_horario_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(nueva_hora_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(hora_actual_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(hora_slc, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(medico_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cambiar_med_btn)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(paciente_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(busqueda_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(buscar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(paciente_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(medico_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cambiar_med_btn))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(jLabel5))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(dia_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(busca_horario_btn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(hora_actual_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(hora_slc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(nueva_hora_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificar_btn)
                    .addComponent(cancelar_btn))
                .addGap(22, 22, 22))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 430, 400));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/medicine.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_btnActionPerformed
        if(busqueda_txt.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "POR FAVOR INGRESE DATO DE BÚSQUEDA","ERROR",JOptionPane.ERROR_MESSAGE);
            busqueda_txt.requestFocus();
        }else if(!busqueda_txt.getText().matches("\\d*"))
        {
            JOptionPane.showMessageDialog(null, "LA BÚSQUEDA SOLO PUEDE CONTENER NÚMEROS","ERROR",JOptionPane.ERROR_MESSAGE);
        }else
        {
            buscaPaciente(busqueda_txt.getText());
        }
    }//GEN-LAST:event_buscar_btnActionPerformed

    private void busca_horario_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busca_horario_btnActionPerformed
        this.hora_slc.removeAllItems();
        String fecha = dia_txt.getCalendar().get(Calendar.YEAR)+"-";
        fecha += (dia_txt.getCalendar().get(Calendar.MONTH)+1)+"-";
        fecha+=dia_txt.getCalendar().get(Calendar.DAY_OF_MONTH);
        horarioDisponible(fecha, idmedico);
    }//GEN-LAST:event_busca_horario_btnActionPerformed

    private void modificar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificar_btnActionPerformed
        String fecha = dia_txt.getCalendar().get(Calendar.YEAR)+"-";
        fecha += (dia_txt.getCalendar().get(Calendar.MONTH)+1)+"-";
        fecha+=dia_txt.getCalendar().get(Calendar.DAY_OF_MONTH);
        boolean respuesta = Consultas.modificaCita(Integer.parseInt(busqueda_txt.getText()),fecha , nueva_hora_txt.getText(),idmedico);
        
        if(respuesta)
        {
            busqueda_txt.setText("");
            busqueda_txt.requestFocus();
            paciente_txt.setText("");
            medico_txt.setText("");
            dia_txt.setDate(null);
            hora_actual_txt.setText("");
            nueva_hora_txt.setText("");
            hora_slc.removeAllItems();
            this.cambiar_med_btn.setEnabled(false);
            this.busca_horario_btn.setEnabled(false);
            this.modificar_btn.setEnabled(false);
            idmedico=0;
            
            JOptionPane.showMessageDialog(null, "CITA ACTUALIZADA","INFORMACIÓN",JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "OCURRIÓ UN ERROR AL ACTUALZIAR LA CITA","ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_modificar_btnActionPerformed

    private void cancelar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar_btnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelar_btnActionPerformed

    private void hora_slcItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_hora_slcItemStateChanged
        nueva_hora_txt.setText((String)hora_slc.getSelectedItem());
    }//GEN-LAST:event_hora_slcItemStateChanged

    private void cambiar_med_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiar_med_btnActionPerformed
        medico = new Medicos();
        medico.setVisible(true);
        medico.setLocationRelativeTo(null);
        medico.op = "cambiar";
    }//GEN-LAST:event_cambiar_med_btnActionPerformed

    
    public static class getHorarioCita{
        
        public static void recibeHorarioCita(int idmed,String medico, String dia, String hora){
            Date nuevoDia = Date.valueOf(dia);
            nueva_hora_txt.setText("");
            idmedico = idmed;
            medico_txt.setText(medico);
            dia_txt.setDate(nuevoDia);
            nueva_hora_txt.setText(hora);
            hora_slc.removeAllItems();
            horarioDisponible(dia, idmedico);
        }
    }
    
    public void buscaPaciente(String doc){
        try {
            Connection conexion= c.getConexion();
            
            PreparedStatement sentencia = conexion.prepareStatement("SELECT pacientes.doc, CONCAT(pacientes.nombre1,' ', pacientes.nombre2,' ', pacientes.apellido1,' ',"+
                    " pacientes.apellido2) AS paciente, CONCAT(medicos.nombre,' ', medicos.apellidos) AS medico,medicos.idmedicos, DATE_FORMAT(citas.hora, '%h: %i %p') AS hora, citas.dia " +
                    "FROM pacientes, medicos, citas " +
                    "WHERE citas.pacientes_docpaciente=? " +
                    "AND pacientes.doc = citas.pacientes_docpaciente " +
                    "AND medicos.idmedicos = citas.medicos_idmedicos " +
                    "AND citas.estado='ASIGNADA'");
            
            sentencia.setString(1, doc);
            
            ResultSet rs = sentencia.executeQuery();
            if(rs.next()){
                this.paciente_txt.setText(rs.getString("paciente"));
                
                this.medico_txt.setText(rs.getString("medico"));
                
                java.util.Date fechaCita = Date.valueOf(rs.getString("dia"));
                this.dia_txt.setDate(fechaCita);
                idmedico=Integer.parseInt(rs.getString("idmedicos"));
                String fecha = dia_txt.getCalendar().get(Calendar.YEAR)+"-";
                fecha += (dia_txt.getCalendar().get(Calendar.MONTH)+1)+"-";
                fecha+=dia_txt.getCalendar().get(Calendar.DAY_OF_MONTH);
                this.hora_actual_txt.setText(rs.getString("hora"));
                this.cambiar_med_btn.setEnabled(true);
                this.busca_horario_btn.setEnabled(true);
                this.modificar_btn.setEnabled(true);
                
                horarioDisponible(fecha, idmedico);
            }
            else{
                JOptionPane.showMessageDialog(null, "LA BÚSQUEDA NO ARROJÓ RESULTADOS, VERIFIQUE");
                this.busqueda_txt.requestFocus();
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }
    
    public static void horarioDisponible(String fecha, int idmed){
        ArrayList<String> horarios = Consultas.selecciona_horario(fecha, idmed);
        
        for(int i=0; i<horarios.size();i++){
            hora_slc.addItem(horarios.get(i));
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificaCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificaCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificaCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificaCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificaCitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton busca_horario_btn;
    private javax.swing.JButton buscar_btn;
    private javax.swing.JTextField busqueda_txt;
    private javax.swing.JButton cambiar_med_btn;
    private javax.swing.JButton cancelar_btn;
    private static com.toedter.calendar.JDateChooser dia_txt;
    private javax.swing.JTextField hora_actual_txt;
    private static javax.swing.JComboBox hora_slc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private static javax.swing.JTextField medico_txt;
    private javax.swing.JButton modificar_btn;
    private static javax.swing.JTextField nueva_hora_txt;
    private javax.swing.JTextField paciente_txt;
    // End of variables declaration//GEN-END:variables
}
